USE hw2_dulher;
INSERT INTO favorite_songs (id, author, song_name, release_year) VALUES (1, 'Tuomas Holopainen', 'Wishmaster', 2000);
INSERT INTO favorite_songs (id, author, song_name, release_year) VALUES (2, 'Willy William', 'Ego', 2015);
INSERT INTO favorite_movies (id, name, producer, release_year) VALUES (1, 'Predator', 'Lawrence Gordon', 1987);
INSERT INTO favorite_movies (id, name, producer, release_year) VALUES (2, 'You''ve Got Mail', 'Lauren Shuler Donner', 1998);
exit;
